### ISSUE TITLE
Database Issue das Verbinden mit übergebenem Passwort funktioniert nicht.

### ISSUE THREAD

**Issue by jhohloch** [Effzumdeh/casestudydhbw#74]
java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Access denied for user 'root'@'localhost' (using password: YES)
Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding'
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:238)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1192)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:620)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:175)
	at org.mariadb.jdbc.Driver.connect(Driver.java:92)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at de.dhbw.backend.DBVerbinder.verbindungHerstellen(DBVerbinder.java:23)
	at de.dhbw.App.main(App.java:17)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:629)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:386)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1187)
	... 7 more

**Comment by bastianhussi** [comment]
du musst in der App-Klasse dein Passwort eintragen (bis jetzt steht 1234 drin, weil das mein Passwort ist)

**Comment by jhohloch** [comment]
@bastianhussi wie finde ich mein Passwort heraus und brauche ich überhaupt eines ?

**Comment by bastianhussi** [comment]
da du XAMPP benutzt hast du wahrscheinlich keins. Hab gerade auch einen Pull Requst erstellt, wo ich das Passwort angepasst habe

**Comment by jhohloch** [comment]
@bastianhussi  es geht jetzt. Nun muss ich mich aber anmelden und die DB ist bis jetzt noch leer. Eine Registrierung funktioniert leider auch nicht.
